### PR TITLE
Updated iiif url to allow for tiles that may have different sizes on …

### PR DESCRIPTION
**Pull request by noahdollar**
…the edges of the image. (Example: https://quod.lib.umich.edu/l/lbc2ic/x-sclp0013/SCLP_0013?lasttype=boolean;lastview=thumbnail;med=1;resnum=13;size=20;sort=lbc2ic_id;start=1;subview=detail;view=entry;rgn1=ic_all;q1=lbc2ic)

### CODE REVIEW

**Comment by lovasoa** [comment]
Thank you very much @noahdollar !

**Comment by noahdollar** [comment]
I believe this will fix issues #250 #264 #248 #233 #260 
Although if anyone continues to have trouble with IIIF please let me know!

**Comment by lovasoa** [comment]
OK. I am going to close these issues, then

**Comment by oZarim** [comment]
Unfortunately this does not fix all of the issues closed... 
Please see my comment in #250.

**Comment by noahdollar** [comment]
From what I remember of the code, I think the fix would be something like:

if sx, sy = data.tilesize, data.tilesize - replace with "full"

and then put a toggle to switch between "full" and "max" for when deprecation happens.

But so far I'm not able to recreate any issues with the examples provided, or I'm not seeing what the issues are. Each one looks like it's loading fully, edges included. Additional comment on #250.

**Pull request merged**
