### PR TITLE
Add: shm.ru & pushkinmuseum.art support

### PR DESCRIPTION
**Pull request by agmmnn**
Support for  **[State Historical Museum](https://catalog.shm.ru/)** and **[The Pushkin Museum](https://pushkinmuseum.art/exposition_collection/index.php?lang=en)**.

Issues: https://github.com/lovasoa/dezoomify/issues/651 https://github.com/lovasoa/dezoomify/issues/690

Example Urls:
https://catalog.shm.ru/entity/OBJECT/2117418
https://catalog.shm.ru/entity/OBJECT/2137429
https://collection.pushkinmuseum.art/en/entity/OBJECT/77609
https://collection.pushkinmuseum.art/entity/OBJECT/787695
https://collection.pushkinmuseum.art/entity/OBJECT/135111

Also implemented here:
https://github.com/agmmnn/pushkin-downloader (next.js app)

### CODE REVIEW

**Comment by lovasoa** [comment]
Thank you, this is a great contribution :)

**Comment by lanaloft** [comment]
Thank you very much!! for your implentation and correction, love it!! 

    Am Mittwoch, 1. März 2023 um 16:53:08 MEZ hat Ophir LOJKINE ***@***.***> Folgendes geschrieben:  
 
 


Thank you, this is a great contribution :)

**Comment by kabalin** [comment]
Same engine, but different domain: https://collection.ethnomuseum.ru/entity/OBJECT/32945 Thinking, may be make this "dezoomer" match regex `\/entity\/OBJECT\/\d+`?

**Comment by lovasoa** [comment]
@agmmnn , do you want to make a pull request?

**Pull request merged**
